//Alert
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
// Register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
// Password Reset
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS'
export const PASSWORD_FAIL = 'PASSWORD_FAIL'

//User Auth
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
//Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
//Profile
export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_ERROR = 'PROFILE_ERROR'

//User
export const GET_USERS = 'GET_USERS'
export const SET_USER_ID = 'SET_USER_ID'
export const GET_USER = 'GET_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const ACTIVATE_USER = 'ACTIVATE_USER'
export const DEACTIVATE_USER = 'DEACTIVATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const USER_ERROR = 'USER_ERROR'

//Company
export const GET_COMPANIES = 'GET_COMPANIES'
export const GET_COMPANY = 'GET_COMPANY'
export const GET_COMPANY_RELATIONSHIPS = 'GET_COMPANY_RELATIONSHIPS'
export const CREATE_COMPANY = 'CREATE_COMPANY'
export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const GET_COMPANY_USERTYPES = 'GET_COMPANY_USERTYPES'
export const DEACTIVATE_COMPANY = 'DEACTIVATE_COMPANY'
export const ACTIVATE_COMPANY = 'ACTIVATE_COMPANY'
export const DELETE_COMPANY = 'DELETE_COMPANY'
export const COMPANY_ERROR = 'COMPANY_ERROR'

//Menu
export const GET_MENUS = 'GET_MENUS'
export const SET_MENU = 'SET_MENU'
export const GET_SUBMENUS = 'GET_SUBMENUS'
export const SET_SUBMENU = 'SET_SUBMENU'
export const GET_SUBSUBMENUS = 'GET_SUBSUBMENUS'
export const SET_SUBSUBMENU = 'SET_SUBSUBMENU'
export const MENU_ERROR = 'MENU_ERROR'

//BCS Events
export const GET_BCSEVENTS = 'GET_BCSEVENTS'
export const GET_BCSEVENT = 'GET_BCSEVENT'
export const CREATE_BCSEVENT = 'CREATE_BCSEVENT'
export const EDIT_BCSEVENT = 'EDIT_BCSEVENT'
export const ACTIVATE_BCSEVENT = 'ACTIVATE_BCSEVENT'
export const DEACTIVATE_BCSEVENT = 'DEACTIVATE_BCSEVENT'
export const DELETE_BCSEVENT = 'DELETE_BCSEVENT'
export const BCSEVENT_ERROR = 'BCSEVENT_ERROR'

//Company Types
export const GET_COMPANYTYPES = 'GET_COMPANYTYPES'
export const GET_COMPANYTYPE = 'GET_COMPANYTYPE'
export const EDIT_COMPANYTYPE = 'EDIT_COMPANYTYPE'
export const CREATE_COMPANYTYPE = 'CREATE_COMPANYTYPE'
export const DELETE_COMPANYTYPE = 'DELETE_COMPANYTYPE'
export const COMPANYTYPE_ERROR = 'COMPANYTYPE_ERROR'

//User Types
export const GET_USERTYPES = 'GET_USERTYPES'
export const GET_USERTYPE = 'GET_USERTYPE'
export const CREATE_USERTYPE = 'CREATE_USERTYPE'
export const DELETE_USERTYPE = 'DELETE_USERTYPE'
export const USERTYPE_ERROR = 'USERTYPE_ERROR'

//Building
export const GET_BUILDINGS = 'GET_BUILDINGS'
export const GET_BUILDING = 'GET_BUILDING'
export const CREATE_BUILDING = 'CREATE_BUILDING'
export const UPDATE_BUILDING = 'UPDATE_BUILDING'
export const DEACTIVATE_BUILDING = 'DEACTIVATE_BUILDING'
export const ACTIVATE_BUILDING = 'ACTIVATE_BUILDING'
export const DELETE_BUILDING = 'DELETE_BUILDING'
export const BUILDING_ERROR = 'BUILDING_ERROR'