//Alert
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
// Register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
// Password Reset
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS'
export const PASSWORD_FAIL = 'PASSWORD_FAIL'

//User Auth
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
//Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
//Profile
export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_ERROR = 'PROFILE_ERROR'

//User
export const GET_USERS = 'GET_USERS'
export const SET_USER_ID = 'SET_USER_ID'
export const GET_USER = 'GET_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const ACTIVATE_USER = 'ACTIVATE_USER'
export const DEACTIVATE_USER = 'DEACTIVATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const USER_ERROR = 'USER_ERROR'

//Company
export const GET_COMPANIES = 'GET_COMPANIES'
export const SET_COMPANY = 'SET_COMPANY'
export const GET_COMPANY_USERTYPES = 'GET_COMPANY_USERTYPES'
export const SET_COMPANY_USERTYPE = 'SET_COMPANY_USERTYPE'
export const COMPANY_ERROR = 'COMPANY_ERROR'

//Menu
export const GET_MENUS = 'GET_MENUS'
export const SET_MENU = 'SET_MENU'
export const GET_SUBMENUS = 'GET_SUBMENUS'
export const SET_SUBMENU = 'SET_SUBMENU'
export const GET_SUBSUBMENUS = 'GET_SUBSUBMENUS'
export const SET_SUBSUBMENU = 'SET_SUBSUBMENU'
export const MENU_ERROR = 'MENU_ERROR'

//BCS Events
export const GET_BCSEVENTS = 'GET_BCSEVENTS'
export const GET_BCSEVENT = 'GET_BCSEVENT'
export const CREATE_BCSEVENT = 'CREATE_BCSEVENT'
export const EDIT_BCSEVENT = 'EDIT_BCSEVENT'
export const ACTIVATE_BCSEVENT = 'ACTIVATE_BCSEVENT'
export const DEACTIVATE_BCSEVENT = 'DEACTIVATE_BCSEVENT'
export const DELETE_BCSEVENT = 'DELETE_BCSEVENT'
export const BCSEVENT_ERROR = 'BCSEVENT_ERROR'
