//Alert
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
// Register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
// Password Reset
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS'
export const PASSWORD_FAIL = 'PASSWORD_FAIL'

//User Auth
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER"
export const UPDATE_CURRENT_USER_ERROR = "UPDATE_CURRENT_USER_ERROR"

//Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
//Profile
export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_ERROR = 'PROFILE_ERROR'

//Menu
export const FETCH_NAV_MENUS = "FETCH_NAV_MENUS"
export const SET_SUBNAV_MENUS = "SET_SUBNAV_MENUS"
export const SET_SIDENAV_MENUS = "SET_SIDENAV_MENUS"
export const MENU_ERROR = 'MENU_ERROR'

// Admin User / Profiles
export const ADMIN_GET_USER_PROFILES = "ADMIN_GET_USER_PROFILES"
export const ADMIN_UPDATE_USER_PROFILES = "ADMIN_UPDATE_USER_PROFILES"
export const ADMIN_SET_USER_PROFILE = "ADMIN_SET_USER_PROFILE"
export const ADMIN_UPDATE_USER_BY_ID = "ADMIN_UPDATE_USER_BY_ID"
export const ADMIN_ACTIVATE_USER = "ADMIN_ACTIVATE_USER"
export const ADMIN_DEACTIVATE_USER = "ADMIN_DEACTIVATE_USER"
export const ADMIN_DELETE_USER = "ADMIN_DELETE_USER"
export const ADMIN_USER_ERROR = "ADMIN_USER_ERROR"

//Admin BCS Events
export const ADMIN_GET_BCSEVENTS = "ADMIN_GET_BCSEVENTS"
export const ADMIN_UPDATE_BCSEVENTS = "ADMIN_UPDATE_BCSEVENTS"
export const ADMIN_CREATE_BCSEVENT = "ADMIN_CREATE_BCSEVENT"
export const ADMIN_UPDATE_BCSEVENT = "ADMIN_UPDATE_BCSEVENT"
export const ADMIN_ACTIVATE_BCSEVENT = "ADMIN_ACTIVATE_BCSEVENT"
export const ADMIN_DEACTIVATE_BCSEVENT = "ADMIN_DEACTIVATE_BCSEVENT"
export const ADMIN_DELETE_BCSEVENT = "ADMIN_DELETE_BCSEVENT"
export const ADMIN_BCSEVENT_ERROR = "ADMIN_BCSEVENT_ERROR"

//Admin Companies
export const ADMIN_GET_COMPANIES = "ADMIN_GET_COMPANIES"
export const ADMIN_UPDATE_COMPANIES = "ADMIN_UPDATE_COMPANIES"
export const ADMIN_CREATE_COMPANY = "ADMIN_CREATE_COMPANY"
export const ADMIN_UPDATE_COMPANY = "ADMIN_UPDATE_COMPANY"
export const ADMIN_ACTIVATE_COMPANY = "ADMIN_ACTIVATE_COMPANY"
export const ADMIN_DEACTIVATE_COMPANY = "ADMIN_DEACTIVATE_COMPANY"
export const ADMIN_DELETE_COMPANY = "ADMIN_DELETE_COMPANY"
export const ADMIN_COMPANY_ERROR = "ADMIN_COMPANY_ERROR"



export const GET_COMPANIES = 'GET_COMPANIES'
export const GET_COMPANY = 'GET_COMPANY'
export const GET_COMPANY_RELATIONSHIPS = 'GET_COMPANY_RELATIONSHIPS'
export const CREATE_COMPANY = 'CREATE_COMPANY'
export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const GET_COMPANY_USERTYPES = 'GET_COMPANY_USERTYPES'
export const DEACTIVATE_COMPANY = 'DEACTIVATE_COMPANY'
export const ACTIVATE_COMPANY = 'ACTIVATE_COMPANY'
export const DELETE_COMPANY = 'DELETE_COMPANY'
export const COMPANY_ERROR = 'COMPANY_ERROR'

//Company Types
export const GET_COMPANYTYPES = 'GET_COMPANYTYPES'
export const GET_COMPANYTYPE = 'GET_COMPANYTYPE'
export const EDIT_COMPANYTYPE = 'EDIT_COMPANYTYPE'
export const CREATE_COMPANYTYPE = 'CREATE_COMPANYTYPE'
export const DELETE_COMPANYTYPE = 'DELETE_COMPANYTYPE'
export const COMPANYTYPE_ERROR = 'COMPANYTYPE_ERROR'

//User Types
export const GET_USERTYPES = 'GET_USERTYPES'
export const GET_USERTYPE = 'GET_USERTYPE'
export const CREATE_USERTYPE = 'CREATE_USERTYPE'
export const DELETE_USERTYPE = 'DELETE_USERTYPE'
export const USERTYPE_ERROR = 'USERTYPE_ERROR'

//Building
export const GET_BUILDINGS = 'GET_BUILDINGS'
export const GET_BUILDING = 'GET_BUILDING'
export const CREATE_BUILDING = 'CREATE_BUILDING'
export const UPDATE_BUILDING = 'UPDATE_BUILDING'
export const DEACTIVATE_BUILDING = 'DEACTIVATE_BUILDING'
export const ACTIVATE_BUILDING = 'ACTIVATE_BUILDING'
export const DELETE_BUILDING = 'DELETE_BUILDING'
export const BUILDING_ERROR = 'BUILDING_ERROR'