const ACCESSTYPES = {
  "COMPANY":{
    "ADMIN":0,
    "ARCHITECTFIRM":1,
    "SCHOOLDISTRICT":2,
    "PUBLIC":99
  },
  "USER":{
    "SUPERADMIN":0,
    "ARCHITECT":1,
    "SUPERINTENDENT":1,
    "ADMIN":2,
    "EDITOR":3,
    "FACILITIESDIRECTOR":3,
    "BUSINESSOFFICIAL":3,
    "AUTHOR":4,
    "MEP":4,
    "CIVIL":4,
    "READER":98,
    "MEMBER":99
  }
}

export {
  ACCESSTYPES
}